name: CI/CD Pipeline
on: ["push"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Install Dependencies
              run: npm install
            - name: Run tests
              run: npm test
            - name: Build & Push docker image
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "narshi" --password-stdin
                docker image build -t narshi/sample-node-app:v1 .
                docker push narshi/sample-node-app:v1
            - name: Installing heroku
              run: |
                npm install -g heroku
                heroku --version
            - name: Login to Heroku CLI
              env: 
                HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
              run: heroku container:login 

            - name: Build and Push Docker Image
              run: |
                docker build -t registry.heroku.com/sample-node-app/web .
                docker tag registry.heroku.com/sample-node-app/web registry.heroku.com/sample-node-app/web
                docker push registry.heroku.com/sample-node-app/web

            - name: Release Docker Image to Heroku
              run: |
                heroku container:release web --app sample-node-app
                heroku open
            # - name: Installing heroku
            #   run: |
            #       npm install -g heroku
            #       heroku --version
            # - name: Deploy to Heroku
            #   run: |
            #     echo "${{ secrets.HEROKU_API_KEY }}" | docker login -u "narshi" --password-stdin registry.heroku.com
            #     heroku container:push web --app sample-node-app
            #     heroku container:release web --app sample-node-app
                
