name: CI/CD Pipeline
on: ["push"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Install Dependencies
              run: npm install
            - name: Run tests
              run: npm test
            - name: Build & Push docker image
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "narshi" --password-stdin
                docker image build -t narshi/sample-node-app:v1 .
                docker push narshi/sample-node-app:v1
            - name: Installing heroku
              run: |
                  npm install -g heroku
                  heroku --version
                  
            - name: Deploy to Heroku
              run: |
                  docker pull narshi/sample-node-app:v1
                  docker tag narshi/sample-node-app:v1 regisry.heroku.com/sample-node-app/web
                  docker push registry.heroku.com/sample-node-app/web
                  heroku container:release web --app sample-node-app
                
